### ISSUE TITLE
missing txt file for training

### ISSUE THREAD

**Issue by vaibhav0195** [HawkAaron/E2E-ASR#1]
Hi i wanted to integrate this transducer model into one of my project, so i wanted to try out to train this model using the script train_rnnt given in the repo.
but i get an error while opening the file 'data/lang/phones.txt'
can you please share this folder ? if not can you please tell me how is the data present in the file 

thank you.

**Comment by HawkAaron** [comment]
Hi, as descripted in README.md, this repo is currently working on TIMIT dataset. 
To train the model, you need to first extract acoustic feature using KALDI toolkit by running `run.sh`, then you will get the directory 'data', which contains file 'data/lang/phones.txt'.
