### ISSUE TITLE
undefined symbol: state

### ISSUE THREAD

**Issue by anonymous-oracle** [HawkAaron/E2E-ASR#13]
Hi. I am trying to train the rnn_t model using the pytorch binding. Would really appreciate if someone can shed some light on the issue I have.

When I run,

"" python3 train_rnnt.py --lr 4e-4 --bi --dropout 0.5 --out exp/rnnt_bi_lr4e-4 --schedule ""

I get the following error:

Traceback (most recent call last):
  File "train_rnnt.py", line 12, in <module>
    from model import Transducer
  File "/home/suhas/E2E-ASR/model.py", line 6, in <module>
    from warprnnt_pytorch import RNNTLoss
  File "/usr/local/lib/python3.6/dist-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 6, in <module>
    from .warp_rnnt import *
ImportError: /usr/local/lib/python3.6/dist-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/warp_rnnt.cpython-36m-x86_64-linux-gnu.so: undefined symbol: state

I really do not know what to make of it.

My system details:
Ubuntu 18.04 LTS, CUDA-10.2
Pytorch built from source

**Comment by HawkAaron** [comment]
Its very strange, could you successfully run the test_gpu & test_cpu inside build dir?

**Comment by anonymous-oracle** [comment]
> Its very strange, could you successfully run the test_gpu & test_cpu inside build dir?

Yes. Here's what the results look like:

```
~/warp-transducer/build$ ./test_cpu 
Running CPU tests
finish small_test 1
finish options_test 1
finish inf_test 1
finished 1
Tests pass
~/warp-transducer/build$ ./test_gpu 
Running gpu tests
finish small_test 1
finish options_test 1
finish inf_test 1
finished 1
Tests pass

```

**Comment by HawkAaron** [comment]
What about `test/test.py`?

**Comment by anonymous-oracle** [comment]
The same ImportError.

```
:~/warp-transducer/pytorch_binding$ python3 test/test.py 
Traceback (most recent call last):
  File "test/test.py", line 17, in <module>
    from warprnnt_pytorch import RNNTLoss
  File "/usr/local/lib/python3.6/dist-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 6, in <module>
    from .warp_rnnt import *
ImportError: /usr/local/lib/python3.6/dist-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/warp_rnnt.cpython-36m-x86_64-linux-gnu.so: undefined symbol: state
```

**Comment by HawkAaron** [comment]
Please reinstall the package.
Make sure to use the same GCC with pytorch building.

BTW, which version of pytorch you used?

**Comment by anonymous-oracle** [comment]
Sorry for the late reply. 
Pytorch version - 1.4.0a0
GCC version - 7.4.0

**Comment by anonymous-oracle** [comment]
And yeah, I'll go with the package versions that you've mentioned in the requirements list

**Comment by Abbsalehi** [comment]
@anonymous-oracle I recently received this error, how could you fix it?
