### ISSUE TITLE
feature_transform makes 69 dimension

### ISSUE THREAD

**Issue by adonisues** [HawkAaron/E2E-ASR#5]
After  "run.sh" and "feature_transform.sh", 69 dim features are given.

It makes error at 54 line in train_rnnt.py .

thank you

**Comment by HawkAaron** [comment]
@adonisues `run.sh` would give you 41 dim log fbank feature, could you please run `feat-to-dim scp:data/train/feats.scp -` to check the feature dimension ?

**Comment by gccyxy** [comment]
> feat-to-dim scp:data/train/feats.scp

I have met the same question, But i do not know what you mean ? can you explain it in detail?

**Comment by gccyxy** [comment]
> After "run.sh" and "feature_transform.sh", 69 dim features are given.
> 
> It makes error at 54 line in train_rnnt.py .
> 
> thank you
I have met the same question, can you teach me how to solve it?

**Comment by gccyxy** [comment]
@HawkAaron I have met the same question, But i do not know what you mean ? can you explain it in detail?

**Comment by gccyxy** [comment]
@HawkAaron 
My shell is as followes:

[root@node02 s5]# feat-to-dim scp:data/train/feats.scp -
feat-to-dim scp:data/train/feats.scp - 
23

what can i do in the next?

**Comment by HawkAaron** [comment]
Please use [this fbank.conf](https://github.com/HawkAaron/E2E-ASR/blob/master/conf/fbank.conf) to extract acoustic feature if you use kaldi.

If not, please follow other recipes to do feature extraction, and then change the input dimension if necessary.
