### ISSUE TITLE
 the question that I use the timit datasets  ,but the rnnt model does not coverage！

### ISSUE THREAD

**Issue by gccyxy** [HawkAaron/E2E-ASR#8]
I adopt this model with timit datasets, but the rnnt model does not coverage, the loss is about 500+, and I want to know the reason which cause it?

**Comment by gccyxy** [comment]
I think the problem is my data may be wrong. Can you provide the data you used in your model? my email 
address is 18710899635@163.com      Thanks a lot!

**Comment by HawkAaron** [comment]
@gccyxy I used `run.sh` to extract 40-dim fbank feature, then `feature_transform.sh` to get 123-dim feature.
Do you have any problem with these scripts?

**Comment by gccyxy** [comment]
> @gccyxy I used `run.sh` to extract 40-dim fbank feature, then `feature_transform.sh` to get 123-dim feature.
> Do you have any problem with these scripts?

 I Have met the problem that when i Run run.sh, I get the mistake that :

[root@node02 s5]# ./run.sh 
============================================================================
                Data & Lexicon & Language Preparation                     
============================================================================
local/timit_data_prep.sh: line 108: wav-to-duration: command not found
 how can solve it ? IS there any problem about my setting path??

**Comment by HawkAaron** [comment]
@gccyxy Its cool. `kaldi/src/featbin/wav-to-duration.cc` that is the command source path. Please compile Kaldi from source if possible.

**Comment by gccyxy** [comment]
./feature_transform.sh: line 10: nnet-initialize: command not found
./feature_transform.sh: line 13: cmvn-to-nnet: command not found
./feature_transform.sh: line 12: nnet-forward: command not found
./feature_transform.sh: line 13: nnet-concat: command not found

What is the reason of it? How can I handle it??

**Comment by gccyxy** [comment]
> @gccyxy Its cool. `kaldi/src/featbin/wav-to-duration.cc` that is the command source path. Please compile Kaldi from source if possible.

./feature_transform.sh: line 10: nnet-initialize: command not found
./feature_transform.sh: line 13: cmvn-to-nnet: command not found
./feature_transform.sh: line 12: nnet-forward: command not found
./feature_transform.sh: line 13: nnet-concat: command not found

What is the reason of it? How can I handle it??

**Comment by gccyxy** [comment]
And I have a Question : If I does not run feature_transform.sh. I just run the 39-dim data for exec your code, Is it working?

**Comment by HawkAaron** [comment]
You may need to change the network input dim.

**Comment by gccyxy** [comment]
> You may need to change the network input dim.



> You may need to change the network input dim.

I have met the problem at the issue <<feature_transform makes 69 dimension>>,  and i have listed the problems. can you teach me how to handle it?

**Comment by HawkAaron** [comment]
Please use [this fbank.conf](https://github.com/HawkAaron/E2E-ASR/blob/master/conf/fbank.conf) to extract acoustic feature if you use kaldi

**Comment by HawkAaron** [comment]
Please use this fbank.conf to extract acoustic feature if you use kaldi.

If not, please follow other recipes to do feature extraction, and then change the input dimension if necessary.

**Comment by gccyxy** [comment]
> Please use this fbank.conf to extract acoustic feature if you use kaldi.
> 
> If not, please follow other recipes to do feature extraction, and then change the input dimension if necessary.

Very Thanks to you !!! 
It is dispirited  that  when I use the 69-dim data for input , however, I met the problem as followes:

 File "/root/anaconda3/lib/python3.7/site-packages/warprnnt_pytorch-0.1-py3.7-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 40, in forward
    grads /= minibatch_size
RuntimeError: CUDA error: an illegal memory access was encountered

Do you have some advise for solving it ？

**Comment by HawkAaron** [comment]
Please make sure PyTorch >= 1.0, and use gcc >= 4.9 to install the python binding.

**Comment by gccyxy** [comment]
> Please make sure PyTorch >= 1.0, and use gcc >= 4.9 to install the python binding.
My gcc  version is 4.8.5 and my PyTorch ==1.1.  Is It does matter ?  What can I do instead of re-installing the gcc version？

**Comment by gccyxy** [comment]
> Please make sure PyTorch >= 1.0, and use gcc >= 4.9 to install the python binding.

It have something related to gcc Version?

**Comment by gccyxy** [comment]
> Please make sure PyTorch >= 1.0, and use gcc >= 4.9 to install the python binding.

If i just use the cpu for training it with about 100 epoches, how long will spend for training ?

**Comment by HawkAaron** [comment]
Please ask whatever you want in a single comment if possible.

And for some reason, only GCC higher than 4.9 (include) is supported for PyTorch CPP extension.

**Comment by gccyxy** [comment]
> Please ask whatever you want in a single comment if possible.
> 
> And for some reason, only GCC higher than 4.9 (include) is supported for PyTorch CPP extension.
All right ! The code can be run in the CPU in my Tesla V100  machine  while GPU failed. If I just try it on CPU , how long will cost for 100 epoches ?

**Comment by HawkAaron** [comment]
Only one hour for TIMIT dataset.
You may run the model on GPU, but calculate RNN-T loss on CPU.

**Comment by gccyxy** [comment]
> Only one hour for TIMIT dataset.
> You may run the model on GPU, but calculate RNN-T loss on CPU.

Thanks a lot for your time !  The information of my training is as followes:
"""""
[Epoch 1 Batch 50] loss 4615.07
[Epoch 1 Batch 100] loss 12606.34
WARNING: Forward backward likelihood mismatch 0.109375
WARNING: Forward backward likelihood mismatch 0.613281
[Epoch 1 Batch 150] loss 9103.89
[Epoch 1 Batch 200] loss 1834.24
[Epoch 1 Batch 250] loss 1286.81
[Epoch 1 Batch 300] loss 1492.13
WARNING: Forward backward likelihood mismatch 0.167969
[Epoch 1 Batch 350] loss 12697.51
WARNING: Forward backward likelihood mismatch 0.253906
WARNING: Forward backward likelihood mismatch 0.105469
[Epoch 1 Batch 400] loss 16489.23
[Epoch 1 Batch 450] loss 16629.37
""""""
From the loss, It seems the model does not coverage. Is there any problem about for training ?

**Comment by HawkAaron** [comment]
Is your `__init__.py` the same as https://github.com/HawkAaron/warp-transducer/blob/master/pytorch_binding/warprnnt_pytorch/__init__.py?

**Comment by gccyxy** [comment]
> Is your `__init__.py` the same as https://github.com/HawkAaron/warp-transducer/blob/master/pytorch_binding/warprnnt_pytorch/__init__.py?

Yes, it is same. I install the warprnnt_pytorch and pass the test_gpu.py.
I am so  puzzled now.  And i am get in this trouble for a long time.  I want to know is there other way to solve it and make the model coverage.

**Comment by gccyxy** [comment]
> Is your `__init__.py` the same as https://github.com/HawkAaron/warp-transducer/blob/master/pytorch_binding/warprnnt_pytorch/__init__.py?
I have done it ! The problem may be that I have changed the code in some aspects by my way, when i run your whole code, it make sense!  However, It is so kind of you ! And many many thanks to you so kind and handsome guy!!!

**Comment by gccyxy** [comment]
> Is your `__init__.py` the same as https://github.com/HawkAaron/warp-transducer/blob/master/pytorch_binding/warprnnt_pytorch/__init__.py?

Hello , HawkAaron:
When I run the decode code, I meet a mistake that which is as follews:
[root@node02 E2E-ASR-master]# python eval.py /home/gcc/test-huawei/E2E-ASR-master/exp/rnnt_bi_lr4e-4/params_epoch109_tr12.74_cv25.52_rejected --ctc --bi --beam 5
Traceback (most recent call last):
  File "eval.py", line 32, in <module>
    model.load_state_dict(torch.load(args.model, map_location='cpu'))
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RNNModel:
	Missing key(s) in state_dict: "lstm.weight_ih_l0", "lstm.weight_hh_l0", "lstm.bias_ih_l0", "lstm.bias_hh_l0", "lstm.weight_ih_l0_reverse", "lstm.weight_hh_l0_reverse", "lstm.bias_ih_l0_reverse", "lstm.bias_hh_l0_reverse", "lstm.weight_ih_l1", "lstm.weight_hh_l1", "lstm.bias_ih_l1", "lstm.bias_hh_l1", "lstm.weight_ih_l1_reverse", "lstm.weight_hh_l1_reverse", "lstm.bias_ih_l1_reverse", "lstm.bias_hh_l1_reverse", "lstm.weight_ih_l2", "lstm.weight_hh_l2", "lstm.bias_ih_l2", "lstm.bias_hh_l2", "lstm.weight_ih_l2_reverse", "lstm.weight_hh_l2_reverse", "lstm.bias_ih_l2_reverse", "lstm.bias_hh_l2_reverse", "linear.weight", "linear.bias". 
	Unexpected key(s) in state_dict: "encoder.lstm.weight_ih_l0", "encoder.lstm.weight_hh_l0", "encoder.lstm.bias_ih_l0", "encoder.lstm.bias_hh_l0", "encoder.lstm.weight_ih_l0_reverse", "encoder.lstm.weight_hh_l0_reverse", "encoder.lstm.bias_ih_l0_reverse", "encoder.lstm.bias_hh_l0_reverse", "encoder.lstm.weight_ih_l1", "encoder.lstm.weight_hh_l1", "encoder.lstm.bias_ih_l1", "encoder.lstm.bias_hh_l1", "encoder.lstm.weight_ih_l1_reverse", "encoder.lstm.weight_hh_l1_reverse", "encoder.lstm.bias_ih_l1_reverse", "encoder.lstm.bias_hh_l1_reverse", "encoder.lstm.weight_ih_l2", "encoder.lstm.weight_hh_l2", "encoder.lstm.bias_ih_l2", "encoder.lstm.bias_hh_l2", "encoder.lstm.weight_ih_l2_reverse", "encoder.lstm.weight_hh_l2_reverse", "encoder.lstm.bias_ih_l2_reverse", "encoder.lstm.bias_hh_l2_reverse", "encoder.linear.weight", "encoder.linear.bias", "embed.weight", "decoder.weight_ih_l0", "decoder.weight_hh_l0", "decoder.bias_ih_l0", "decoder.bias_hh_l0", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias". 

What is the reason of it ? I have setted the best params of model path, but it failed.

**Comment by gccyxy** [comment]
> Is your `__init__.py` the same as https://github.com/HawkAaron/warp-transducer/blob/master/pytorch_binding/warprnnt_pytorch/__init__.py?

**Comment by gccyxy** [comment]
@HawkAaron   I have met a mistake that the result decoded  includes [52,53,54,55,56,57,......],
while the rephone length is just 51. Hence，I met a bug as followes:
the one of y (the result of decoded ) is as followes:
(53, 59, 53, 59, 56, 53, 43, 53, 43, 53, 5, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 25, 53, 25, 53, 48, 53, 59, 53, 25, 53, 43, 53, 43, 53, 43, 53, 59, 53, 59, 31, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 43, 53, 25, 53, 25, 53, 43, 53, 35, 53, 43, 53, 31, 53, 43, 53, 43, 53, 31, 53, 43, 53, 48, 53, 59, 5, 53, 32, 53, 43, 53, 59, 43, 31, 53, 59, 53, 25, 53, 25, 5, 25, 32, 53, 43, 53, 43, 53, 43, 53, 43, 53, 59, 53, 31, 53, 59, 53, 59)
Traceback (most recent call last):
  File "eval.py", line 93, in <module>
    decode()
  File "eval.py", line 84, in decode
    y = [pmap[rephone[i]] for i in y]
  File "eval.py", line 84, in <listcomp>
    y = [pmap[rephone[i]] for i in y]
KeyError: 53

Why my pmap'(or y) length is not as long as the rephone ?
